# Generated by Django 6.0.3 on 2026-04-04 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('caissier', 'Caissier'), ('chauffeur', 'Chauffeur')], max_length=20)),
                ('mot_de_passe', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('destination', models.CharField(max_length=100)),
                ('nombre_passagers', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('carburant', 'Carburant'), ('reparation', 'Réparation'), ('autre', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('trajet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trajet')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('chauffeur', models.ForeignKey(limit_choices_to={'role': 'chauffeur'}, on_delete=django.db.models.deletion.CASCADE, to='core.utilisateur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicule')),
            ],
        ),
    ]
