# Generated by Django 6.0.3 on 2026-04-13 11:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('journalier', 'Journalier'), ('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('recettes_totales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('depenses_totales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('benefice_net', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('marge_beneficiaire', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepenseJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('details', models.JSONField(default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecetteJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nombre_trajets', models.IntegerField(default=0)),
                ('nombre_passagers_total', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('taxi_brousse', 'Taxi Brousse'), ('bus', 'Bus'), ('minibus', 'Minibus')], max_length=20)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('annee_fabrication', models.IntegerField()),
                ('nombre_places', models.IntegerField()),
                ('etat', models.CharField(choices=[('disponible', 'Disponible'), ('en_maintenance', 'En maintenance'), ('en_trajet', 'En trajet')], default='disponible', max_length=20)),
                ('kilometrage', models.IntegerField(default=0)),
                ('date_achat', models.DateField()),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('caissier', 'Caissier'), ('chauffeur', 'Chauffeur')], default='chauffeur', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=15)),
                ('adresse', models.TextField(blank=True)),
                ('date_embauche', models.DateField(auto_now_add=True)),
                ('salaire_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('est_actif', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CommissionChauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('recettes_realisees', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taux_commission', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('montant_commission', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('est_paye', models.BooleanField(default=False)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('chauffeur', models.ForeignKey(limit_choices_to={'role': 'chauffeur'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_depart', models.TimeField()),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('destination', models.CharField(max_length=100)),
                ('origine', models.CharField(default='Dakar', max_length=100)),
                ('nombre_passagers', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance en km', max_digits=10)),
                ('status', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('chauffeur', models.ForeignKey(limit_choices_to={'role': 'chauffeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicule')),
            ],
            options={
                'ordering': ['-date', '-heure_depart'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('carburant', 'Carburant'), ('reparation', 'Réparation'), ('entretien', 'Entretien'), ('assurance', 'Assurance'), ('vignette', 'Vignette'), ('amende', 'Amende'), ('autre', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('quantite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fournisseur', models.CharField(blank=True, max_length=100)),
                ('facture', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('trajet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trajet')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('motif_fin', models.TextField(blank=True)),
                ('chauffeur', models.ForeignKey(limit_choices_to={'role': 'chauffeur'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicule')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
    ]
