# Generated by Django 6.0.3 on 2026-05-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Benefice',
        ),
        migrations.AlterModelOptions(
            name='affectation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trajet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='commissionchauffeur',
            name='date_paiement',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='facture',
        ),
        migrations.RemoveField(
            model_name='depensejournaliere',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='depensejournaliere',
            name='details',
        ),
        migrations.RemoveField(
            model_name='recettejournaliere',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='recettejournaliere',
            name='date_modification',
        ),
        migrations.AlterField(
            model_name='depense',
            name='quantite',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantité en litres ou unités', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='origine',
            field=models.CharField(default='Antananarivo', max_length=100),
        ),
    ]
